" .bashrc
" >^.^<

let mapleader=" "
let maplocalleader = "\\"

nnoremap <leader>sv :source $MYVIMRC<cr>

" PLUGINS
execute pathogen#infect()

" Syntax Highlighting
filetype plugin indent on
syntax on

" Color Theme
colorscheme tomorrow-night
" Default layout
set lines=50 columns=100
set textwidth=80
set colorcolumn=+1
" Set line numbering
set number
set numberwidth=5
" Use spaces, instead of tabs
set nowrap
set expandtab
" Smart tabs
set smartindent
set autoindent
set smarttab
" 1 tab == 2 spaces
set shiftwidth=2
set tabstop=2
" Keep more info in memory
set hidden
set history=100

" Delete whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Better Search
set hlsearch
" Show matching parens
set showmatch

" Keep status bar in view
set laststatus=2
set timeoutlen=50

" Learn VIM Script the Hard Way examples
" Upcase current word
inoremap <c-u> <esc>viwU<esc>ea
" Display extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·
